# https://travis-ci.org/trivago/Protector
sudo: false
os:
  - linux
language: python
env:
  global:
    - MAIN_VERSION=2.7
python:
  - "2.7"
  - "pypy"
install:
  - "pip install nose"
  - "pip install ."
script:
  - python setup.py nosetests
after_success:
  - pip install coveralls
  - coverage run --source=protector setup.py test && coveralls
